name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup BATS
      uses: mig4/setup-bats@v1.0.1
    - name: Test
      run: |
        cd bash
        bats wikipedia.bats
        cd ..

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install metaflow pandas matplotlib notebook
    - name: Run tests and check metaflows
      run: |
        cd python
        python tests.py
        python stats.py show
        python stats.py run --domains '["zu", "zu.d", "zu.m"]'
        cd ..

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Compile project
      run: |
        cd scala
        sbt test
        cd ..
